# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_dtm_model_rcpp <- function(k, t, alpha = 0.1, beta = 0.01, gamma = 0.1, random_seed = -1L) {
    .Call('_DTModelR_create_dtm_model_rcpp', PACKAGE = 'DTModelR', k, t, alpha, beta, gamma, random_seed)
}

add_document_rcpp <- function(model_ptr, words, time_slice) {
    invisible(.Call('_DTModelR_add_document_rcpp', PACKAGE = 'DTModelR', model_ptr, words, time_slice))
}

train_model_rcpp <- function(model_ptr, iterations, calc_perplexity = FALSE, show_progress = TRUE) {
    invisible(.Call('_DTModelR_train_model_rcpp', PACKAGE = 'DTModelR', model_ptr, iterations, calc_perplexity, show_progress))
}

get_topic_word_dist_rcpp <- function(model_ptr, topic, time) {
    .Call('_DTModelR_get_topic_word_dist_rcpp', PACKAGE = 'DTModelR', model_ptr, topic, time)
}

get_doc_topic_dist_rcpp <- function(model_ptr, doc_id) {
    .Call('_DTModelR_get_doc_topic_dist_rcpp', PACKAGE = 'DTModelR', model_ptr, doc_id)
}

get_vocabulary_rcpp <- function(model_ptr) {
    .Call('_DTModelR_get_vocabulary_rcpp', PACKAGE = 'DTModelR', model_ptr)
}

get_perplexity_rcpp <- function(model_ptr) {
    .Call('_DTModelR_get_perplexity_rcpp', PACKAGE = 'DTModelR', model_ptr)
}

get_model_info_rcpp <- function(model_ptr) {
    .Call('_DTModelR_get_model_info_rcpp', PACKAGE = 'DTModelR', model_ptr)
}

set_word_prior_rcpp <- function(model_ptr, topic, words, priors) {
    invisible(.Call('_DTModelR_set_word_prior_rcpp', PACKAGE = 'DTModelR', model_ptr, topic, words, priors))
}

get_top_words_rcpp <- function(model_ptr, topic, time, top_n = 10L) {
    .Call('_DTModelR_get_top_words_rcpp', PACKAGE = 'DTModelR', model_ptr, topic, time, top_n)
}

save_model_rcpp <- function(model_ptr, filename) {
    invisible(.Call('_DTModelR_save_model_rcpp', PACKAGE = 'DTModelR', model_ptr, filename))
}

load_model_rcpp <- function(filename) {
    .Call('_DTModelR_load_model_rcpp', PACKAGE = 'DTModelR', filename)
}

get_num_docs_rcpp <- function(model_ptr) {
    .Call('_DTModelR_get_num_docs_rcpp', PACKAGE = 'DTModelR', model_ptr)
}

get_num_topics_rcpp <- function(model_ptr) {
    .Call('_DTModelR_get_num_topics_rcpp', PACKAGE = 'DTModelR', model_ptr)
}

get_num_times_rcpp <- function(model_ptr) {
    .Call('_DTModelR_get_num_times_rcpp', PACKAGE = 'DTModelR', model_ptr)
}

get_vocab_size_rcpp <- function(model_ptr) {
    .Call('_DTModelR_get_vocab_size_rcpp', PACKAGE = 'DTModelR', model_ptr)
}

get_alpha_rcpp <- function(model_ptr) {
    .Call('_DTModelR_get_alpha_rcpp', PACKAGE = 'DTModelR', model_ptr)
}

get_beta_rcpp <- function(model_ptr) {
    .Call('_DTModelR_get_beta_rcpp', PACKAGE = 'DTModelR', model_ptr)
}

get_gamma_rcpp <- function(model_ptr) {
    .Call('_DTModelR_get_gamma_rcpp', PACKAGE = 'DTModelR', model_ptr)
}

